apiVersion: kustomize.config.k8s.io/v1beta1
helmCharts:
- name: external-secrets
  namespace: external-secrets
  releaseName: external-secrets
  repo: https://charts.external-secrets.io
  valuesFile: dev-values.yaml
  version: 1.1.0
images:
- name: oci.external-secrets.io/external-secrets/external-secrets
  newTag: v1.1.0
kind: Kustomization
